version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13.2
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - ./.env

  social_network_fastapi:
    container_name: social_network_fastapi
    build: .
    restart: always
    ports:
      - 8000:8000
    command: bash -c "alembic upgrade head && exec uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  db_volume:
